# Model arguments
model_name_or_path: plaguss/zephyr-7b-spin-iter0-v0

# Data training arguments
dataset_mixer:
  argilla/10k_prompts_SPIN_iter0_zephyr_top: 1.0
  argilla/10k_prompts_SPIN_iter1_zephyr_top: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 12

# Trainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 25
gradient_accumulation_steps: 2
gradient_checkpointing: true
hub_model_id: zephyr-7b-spin-iter1-v0
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 2
optim: rmsprop
output_dir: outputs
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
push_to_hub: true
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1
report_to:
- wandb